CREATE TABLE "report_images" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" text NOT NULL,
	"user_id" text NOT NULL,
	"cloudinary_public_id" text NOT NULL,
	"cloudinary_url" text NOT NULL,
	"cloudinary_secure_url" text NOT NULL,
	"original_filename" text,
	"display_name" text,
	"image_role" text DEFAULT 'other' NOT NULL,
	"caption" text,
	"alt_text" text,
	"is_primary" boolean DEFAULT false NOT NULL,
	"include_in_pdf" boolean DEFAULT true NOT NULL,
	"include_in_html" boolean DEFAULT true NOT NULL,
	"include_in_buyer_report" boolean DEFAULT true NOT NULL,
	"include_in_seller_report" boolean DEFAULT true NOT NULL,
	"section_key" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"width" integer,
	"height" integer,
	"aspect_ratio" numeric,
	"file_size" integer,
	"mime_type" text,
	"source_type" text DEFAULT 'uploaded' NOT NULL,
	"source_ref_id" text,
	"is_panoramic" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"deleted_at" timestamp
);
