import { Router } from "express";
import { requireAuth } from "../../middlewares/auth";
import {
  db, reportSectionsTable, reportExportsTable, cafesTable, reportVersionsTable,
} from "@workspace/db";
import { eq, asc, and } from "drizzle-orm";
import { logger } from "../../lib/logger";

// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require("pdfkit");

const router = Router();

const BLUE_ACC = "#3B82F6";
const WHITE    = "#FFFFFF";
const LIGHT    = "#CBD5E1";
const MUTED    = "#8B9CB8";

// ─── PDF generation handler ───────────────────────────────────────────────────
// Shared by GET and POST /api/report-exports/pdf/:listingId
// Query: mode=seller|buyer, versionId=<uuid> (optional)
async function handlePdf(req: any, res: any): Promise<void> {
  const userId    = req.user!.id as string;
  const listingId = req.params.listingId as string;
  const mode      = (req.query.mode as string | undefined) ?? "seller";
  const versionId = req.query.versionId as string | undefined;

  try {
    const [cafe] = await db
      .select({ id: cafesTable.id, name: cafesTable.name })
      .from(cafesTable)
      .where(and(eq(cafesTable.listingId, listingId), eq(cafesTable.ownerId, userId)))
      .limit(1);

    if (!cafe) {
      res.status(403).json({ error: "Not authorised to export this listing" });
      return;
    }

    // When versionId is supplied, resolve sections from the published snapshot
    // rather than live state — ensuring the PDF represents a specific version.
    let allSections: any[];
    if (versionId) {
      const [version] = await db
        .select()
        .from(reportVersionsTable)
        .where(and(eq(reportVersionsTable.id, versionId), eq(reportVersionsTable.ownerId, userId)))
        .limit(1);
      if (!version) {
        res.status(404).json({ error: "Version not found or access denied" });
        return;
      }
      allSections = ((version.snapshotJson ?? []) as any[]).sort(
        (a: any, b: any) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0),
      );
    } else {
      allSections = await db
        .select()
        .from(reportSectionsTable)
        .where(eq(reportSectionsTable.listingId, listingId))
        .orderBy(asc(reportSectionsTable.sortOrder));
    }

    const sections = allSections.filter((s: any) => {
      if (!s.includeInPdf) return false;
      if (s.visibility === "hidden") return false;
      if (mode === "buyer" && s.visibility === "seller_only") return false;
      return true;
    });

    const businessName = cafe.name ?? "Business";
    const modeLabel    = mode === "seller" ? "Seller Copy" : "Buyer Copy";
    const dateStr      = new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" });
    const filename     = `im-report-${listingId.slice(0, 8)}-${mode}.pdf`;

    const doc = new PDFDocument({
      size: "A4",
      margin: 0,
      info: {
        Title:    `Information Memorandum — ${businessName}`,
        Author:   "Exit360",
        Subject:  "Confidential Business Information Memorandum",
        Keywords: "information memorandum, business for sale, exit360",
      },
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Cache-Control", "no-cache");
    doc.pipe(res);

    const PAGE_W   = 595.28;
    const PAGE_H   = 841.89;
    const MARGIN   = 56;
    const CONTENT_W = PAGE_W - MARGIN * 2;
    const DARK     = "#070F1C";
    const DARK_MID = "#0F2040";
    const BORDER   = "#1E3A5C";

    // ── Helper: header / footer ───────────────────────────────────────────────
    function addHeaderFooter(pageNum: number, totalPages: number) {
      doc.save().rect(0, 0, PAGE_W, 36).fill("#0A1828").restore();
      doc.font("Helvetica-Bold").fontSize(7).fillColor(MUTED)
        .text(businessName, MARGIN, 14, { width: CONTENT_W / 2 });
      doc.font("Helvetica").fontSize(7).fillColor(MUTED)
        .text("Information Memorandum", MARGIN + CONTENT_W / 2, 14, {
          width: CONTENT_W / 2, align: "right",
        });
      doc.save().rect(0, PAGE_H - 36, PAGE_W, 36).fill("#0A1828").restore();
      doc.font("Helvetica").fontSize(7).fillColor(MUTED)
        .text(`Confidential Business Profile · Generated by Exit360`, MARGIN, PAGE_H - 22, {
          width: CONTENT_W - 80,
        })
        .text(`Page ${pageNum} of ${totalPages}`, MARGIN, PAGE_H - 22, { width: CONTENT_W, align: "right" });
    }

    // ── Cover Page ────────────────────────────────────────────────────────────
    doc.rect(0, 0, PAGE_W, PAGE_H).fill(DARK);
    doc.save().rect(0, 0, PAGE_W, 6).fill(BLUE_ACC).restore();

    doc.font("Helvetica-Bold").fontSize(9).fillColor(BLUE_ACC)
      .text("CONFIDENTIAL", MARGIN, 60, { width: CONTENT_W, align: "center" });

    doc.font("Helvetica-Bold").fontSize(26).fillColor(WHITE)
      .text("Information Memorandum", MARGIN, 86, { width: CONTENT_W, align: "center" });

    doc.font("Helvetica-Bold").fontSize(20).fillColor("#60A5FA")
      .text(businessName, MARGIN, 126, { width: CONTENT_W, align: "center" });

    doc.font("Helvetica").fontSize(10).fillColor(MUTED)
      .text("Prepared by Exit360 · Verified Business Profile", MARGIN, 162, {
        width: CONTENT_W, align: "center",
      });

    doc.save().moveTo(MARGIN, 192).lineTo(PAGE_W - MARGIN, 192)
      .lineWidth(1).strokeColor(BORDER).stroke().restore();

    doc.rect(MARGIN, 210, CONTENT_W, 120).fill(DARK_MID);

    const metaItems = [
      ["Listing Reference", listingId.slice(0, 8).toUpperCase()],
      ["Report Mode", modeLabel],
      ["Date Prepared", dateStr],
      ["Sections", `${sections.length} sections`],
    ];
    metaItems.forEach(([label, value], i) => {
      const col = i < 2 ? 0 : 1;
      const row = i % 2;
      const x = MARGIN + 16 + col * (CONTENT_W / 2);
      const y = 226 + row * 42;
      doc.font("Helvetica").fontSize(8).fillColor(MUTED).text(label.toUpperCase(), x, y);
      doc.font("Helvetica-Bold").fontSize(12).fillColor(WHITE).text(value, x, y + 12);
    });

    doc.font("Helvetica").fontSize(9).fillColor(MUTED)
      .text(
        "This document is confidential and intended solely for the named recipient. Unauthorised disclosure is strictly prohibited.",
        MARGIN, 370, { width: CONTENT_W, align: "center", lineGap: 3 },
      );

    doc.font("Helvetica-Bold").fontSize(16).fillColor(BLUE_ACC)
      .text("Exit360", MARGIN, PAGE_H - 120, { width: CONTENT_W, align: "center" });
    doc.font("Helvetica").fontSize(9).fillColor(MUTED)
      .text("exit360.com.au", MARGIN, PAGE_H - 100, { width: CONTENT_W, align: "center" });

    // ── Table of Contents ─────────────────────────────────────────────────────
    const totalPages = 2 + sections.length; // cover + TOC + one page per section
    doc.addPage({ size: "A4", margin: 0 });
    doc.rect(0, 0, PAGE_W, PAGE_H).fill(DARK);
    addHeaderFooter(2, totalPages);

    doc.font("Helvetica-Bold").fontSize(16).fillColor(WHITE)
      .text("Table of Contents", MARGIN, 56);
    doc.save().moveTo(MARGIN, 80).lineTo(PAGE_W - MARGIN, 80)
      .lineWidth(0.5).strokeColor(BORDER).stroke().restore();

    let tocY = 94;
    sections.forEach((s, idx) => {
      if (tocY > PAGE_H - 80) return;
      doc.font("Helvetica-Bold").fontSize(8).fillColor(MUTED)
        .text(`${String(idx + 1).padStart(2, "0")}`, MARGIN, tocY, { width: 24 });
      doc.font("Helvetica").fontSize(10).fillColor(LIGHT)
        .text(s.title, MARGIN + 28, tocY, { width: CONTENT_W - 50 });
      doc.font("Helvetica").fontSize(8).fillColor(MUTED)
        .text(`${idx + 3}`, MARGIN, tocY, { width: CONTENT_W, align: "right" });
      tocY += 18;
    });

    // ── Section Pages ─────────────────────────────────────────────────────────
    sections.forEach((section, idx) => {
      doc.addPage({ size: "A4", margin: 0 });
      doc.rect(0, 0, PAGE_W, PAGE_H).fill(DARK);
      addHeaderFooter(idx + 3, totalPages);

      const sY = 50;

      doc.save().rect(MARGIN, sY, 4, 26).fill(BLUE_ACC).restore();

      doc.font("Helvetica-Bold").fontSize(7).fillColor(BLUE_ACC)
        .text(`${String(idx + 1).padStart(2, "0")}`, MARGIN + 10, sY + 2);

      doc.font("Helvetica-Bold").fontSize(15).fillColor(WHITE)
        .text(section.title, MARGIN + 30, sY, { width: CONTENT_W - 30 });

      if (section.subtitle) {
        doc.font("Helvetica").fontSize(9).fillColor(MUTED)
          .text(section.subtitle, MARGIN + 30, sY + 22, { width: CONTENT_W - 30 });
      }

      doc.save().moveTo(MARGIN, sY + 42).lineTo(PAGE_W - MARGIN, sY + 42)
        .lineWidth(0.5).strokeColor(BORDER).stroke().restore();

      let bodyY = sY + 56;

      if (section.body) {
        const paras = section.body.split(/\n{2,}/).filter(Boolean);
        for (const para of paras) {
          if (bodyY > PAGE_H - 80) break;
          doc.font("Helvetica").fontSize(10).fillColor(LIGHT)
            .text(para.trim(), MARGIN, bodyY, { width: CONTENT_W, lineGap: 3 });
          bodyY = doc.y + 10;
        }
      }

      const bullets = Array.isArray(section.bulletPoints) ? (section.bulletPoints as string[]) : [];
      if (bullets.length > 0 && bodyY < PAGE_H - 80) {
        bodyY += 6;
        for (const b of bullets) {
          if (!b.trim() || bodyY > PAGE_H - 80) continue;
          doc.save().circle(MARGIN + 5, bodyY + 4.5, 2.5).fill(BLUE_ACC).restore();
          doc.font("Helvetica").fontSize(10).fillColor(LIGHT)
            .text(b.trim(), MARGIN + 16, bodyY, { width: CONTENT_W - 16, lineGap: 2 });
          bodyY = doc.y + 4;
        }
      }

      // ── Chart visualisation ─────────────────────────────────────────────────
      // Draw a simple pdfkit-native chart if chartData is present for the
      // section's key. Falls back to a compact data table for Radar-type charts.
      if (section.chartData && bodyY < PAGE_H - 120) {
        const rawData = typeof section.chartData === "string"
          ? (() => { try { return JSON.parse(section.chartData); } catch { return null; } })()
          : section.chartData;

        if (rawData && Array.isArray(rawData) && rawData.length > 0) {
          bodyY += 10;
          const CHART_H   = 120;
          const CHART_Y   = bodyY;
          const CHART_MAX_W = CONTENT_W;
          const BAR_PAD  = 6;
          const COLORS   = ["#3B82F6", "#10B981", "#8B5CF6", "#F59E0B", "#EC4899", "#14B8A6", "#F97316", "#6366F1"];
          const sk = section.sectionKey as string;

          // Helper: format money / number
          function fmtV(v: unknown): string {
            const n = Number(v ?? 0);
            if (!isFinite(n)) return String(v ?? "");
            if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
            if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
            if (n === Math.floor(n)) return n.toLocaleString();
            return n.toFixed(1);
          }

          // Radar-style sections → render as horizontal score bars
          const isRadar = sk === "lease_premises_summary" || sk === "business_health_score";
          const isPie   = sk === "revenue_stream_breakdown" || sk === "plant_equipment_summary";
          const isHBar  = sk === "division_breakdown" || sk === "buyer_access_confidentiality";

          if (isRadar) {
            // Score table: subject + filled bar (0–100)
            doc.font("Helvetica-Bold").fontSize(7).fillColor(MUTED)
              .text("SCORE BREAKDOWN", MARGIN, bodyY);
            bodyY += 12;
            const rowH = 14;
            rawData.slice(0, 8).forEach((row: Record<string, unknown>) => {
              const label = String(row["subject"] ?? row["name"] ?? "");
              const score = Math.min(100, Math.max(0, Number(row["score"] ?? row["value"] ?? 0)));
              if (bodyY > PAGE_H - 60) return;
              doc.font("Helvetica").fontSize(8).fillColor(LIGHT)
                .text(label, MARGIN, bodyY, { width: 100 });
              const barX = MARGIN + 110;
              const barW = CONTENT_W - 120;
              doc.save().rect(barX, bodyY + 1, barW, 9).fill("#1E3A5C").restore();
              doc.save().rect(barX, bodyY + 1, barW * (score / 100), 9).fill(BLUE_ACC).restore();
              doc.font("Helvetica-Bold").fontSize(7).fillColor(WHITE)
                .text(`${score}`, barX + barW + 4, bodyY + 1, { width: 30 });
              bodyY += rowH;
            });

          } else if (isPie) {
            // Render pie data as horizontal bar legend
            const total = rawData.reduce((s: number, r: Record<string, unknown>) => s + Number(r["value"] ?? 0), 0) || 1;
            doc.font("Helvetica-Bold").fontSize(7).fillColor(MUTED)
              .text("DISTRIBUTION", MARGIN, bodyY);
            bodyY += 12;
            rawData.slice(0, 8).forEach((row: Record<string, unknown>, ci: number) => {
              if (bodyY > PAGE_H - 60) return;
              const label = String(row["name"] ?? "");
              const val   = Number(row["value"] ?? 0);
              const pct   = val / total;
              const barW  = CONTENT_W - 130;
              doc.save().rect(MARGIN, bodyY + 2, 8, 8).fill(COLORS[ci % COLORS.length]).restore();
              doc.font("Helvetica").fontSize(8).fillColor(LIGHT)
                .text(label, MARGIN + 12, bodyY, { width: 110 });
              doc.save().rect(MARGIN + 130, bodyY + 1, barW, 9).fill("#1E3A5C").restore();
              doc.save().rect(MARGIN + 130, bodyY + 1, Math.max(4, barW * pct), 9).fill(COLORS[ci % COLORS.length]).restore();
              doc.font("Helvetica").fontSize(7).fillColor(MUTED)
                .text(`${(pct * 100).toFixed(0)}%`, MARGIN + 130 + barW + 4, bodyY + 1, { width: 30 });
              bodyY += 14;
            });

          } else if (isHBar) {
            // Horizontal bar chart (division_breakdown, buyer funnel)
            const valKey  = (rawData[0] && Object.keys(rawData[0]).find(k => k !== "name" && k !== "stage")) ?? "value";
            const lblKey  = rawData[0] && ("stage" in rawData[0] ? "stage" : "name");
            const maxVal  = Math.max(...rawData.map((r: Record<string, unknown>) => Number(r[valKey] ?? 0))) || 1;
            doc.font("Helvetica-Bold").fontSize(7).fillColor(MUTED)
              .text(String(valKey).toUpperCase(), MARGIN, bodyY);
            bodyY += 12;
            rawData.slice(0, 8).forEach((row: Record<string, unknown>, ci: number) => {
              if (bodyY > PAGE_H - 60) return;
              const label = String(row[lblKey] ?? "");
              const val   = Number(row[valKey] ?? 0);
              const barW  = CONTENT_W - 130;
              doc.font("Helvetica").fontSize(8).fillColor(LIGHT)
                .text(label, MARGIN, bodyY, { width: 120 });
              doc.save().rect(MARGIN + 130, bodyY + 1, barW, 9).fill("#1E3A5C").restore();
              doc.save().rect(MARGIN + 130, bodyY + 1, Math.max(4, barW * (val / maxVal)), 9).fill(COLORS[ci % COLORS.length]).restore();
              doc.font("Helvetica").fontSize(7).fillColor(MUTED)
                .text(fmtV(val), MARGIN + 130 + barW + 4, bodyY + 1, { width: 50 });
              bodyY += 14;
            });

          } else {
            // Vertical bar chart (default: app_valuation_summary, verified_revenue_sources, etc.)
            const valKey  = (rawData[0] && Object.keys(rawData[0]).find(k => k !== "name" && k !== "source" && k !== "type")) ?? "value";
            const lblKey  = rawData[0] && ("source" in rawData[0] ? "source" : "name");
            const maxVal  = Math.max(...rawData.map((r: Record<string, unknown>) => Number(r[valKey] ?? 0))) || 1;
            const n       = Math.min(rawData.length, 8);
            const barW    = Math.floor((CHART_MAX_W - BAR_PAD * (n + 1)) / n);
            doc.font("Helvetica-Bold").fontSize(7).fillColor(MUTED)
              .text(String(valKey).toUpperCase(), MARGIN, CHART_Y);
            rawData.slice(0, n).forEach((row: Record<string, unknown>, ci: number) => {
              const val    = Number(row[valKey] ?? 0);
              const ratio  = val / maxVal;
              const bx     = MARGIN + BAR_PAD + ci * (barW + BAR_PAD);
              const bh     = Math.max(4, CHART_H * ratio);
              const by     = CHART_Y + 10 + CHART_H - bh;
              doc.save().rect(bx, by, barW, bh).fill(COLORS[ci % COLORS.length]).restore();
              // x-axis label
              doc.font("Helvetica").fontSize(7).fillColor(MUTED)
                .text(String(row[lblKey] ?? "").slice(0, 12), bx, CHART_Y + 10 + CHART_H + 3, { width: barW + BAR_PAD, align: "center" });
              // value label on bar top
              doc.font("Helvetica-Bold").fontSize(6).fillColor(WHITE)
                .text(fmtV(val), bx, Math.max(CHART_Y + 12, by - 9), { width: barW, align: "center" });
            });
            bodyY = CHART_Y + 10 + CHART_H + 20;
          }

          bodyY += 6;
        }
      }

      if (!section.body && !bullets.length && (!section.chartData || !Array.isArray(section.chartData))) {
        doc.font("Helvetica-Oblique").fontSize(9).fillColor(MUTED)
          .text("This section has not yet been completed.", MARGIN, bodyY, { width: CONTENT_W });
      }
    });

    // ── Audit log ─────────────────────────────────────────────────────────────
    db.insert(reportExportsTable).values({
      listingId,
      ownerId:    userId,
      exportType: mode === "seller" ? "pdf_seller" : "pdf_buyer",
    }).catch((e) => logger.warn({ err: e }, "PDF export audit log failed"));

    doc.end();
  } catch (err: unknown) {
    const e = err as Error & { status?: number };
    logger.error({ err: e }, "PDF export failed");
    if (!res.headersSent) {
      res.status(e.status ?? 500).json({ error: e.message ?? "Failed to generate PDF" });
    }
  }
}

router.get("/report-exports/pdf/:listingId",  requireAuth, handlePdf);
router.post("/report-exports/pdf/:listingId", requireAuth, handlePdf);

// ─── GET /api/report-exports/pdf-public/:listingId ───────────────────────────
// Public buyer-mode PDF.
// Without ?accessToken: includes only visibility=public sections (teaser).
// With valid ?accessToken (OTP-verified buyer JWT): also includes approved_buyers
// sections, matching the section set the buyer can see in the HTML report.
router.get("/report-exports/pdf-public/:listingId", async (req: any, res: any): Promise<void> => {
  const listingId     = req.params.listingId as string;
  const rawToken      = req.query.accessToken as string | undefined;
  let   buyerUnlocked = false;

  if (rawToken) {
    try {
      const { jwtVerify } = await import("jose");
      const secret = process.env.JWT_SECRET;
      if (secret) {
        const { payload } = await jwtVerify(rawToken, new TextEncoder().encode(secret));
        // Accept buyer-report-access tokens issued for this specific listing
        // A valid JWT with the correct type + listingId is sufficient proof of access.
        // The JWT is issued only after OTP verification and grant lookup succeed, so
        // its existence + validity is equivalent to a live grant check.
        if (
          (payload.type === "buyer-report-access" || payload.type === "seller-preview") &&
          payload.listingId === listingId
        ) {
          buyerUnlocked = true;
        }
      }
    } catch { /* invalid token — treat as unauthenticated */ }
  }

  try {
    const allSections = await db
      .select()
      .from(reportSectionsTable)
      .where(eq(reportSectionsTable.listingId, listingId))
      .orderBy(asc(reportSectionsTable.sortOrder));

    const sections = allSections.filter((s) => {
      if (!s.includeInPdf) return false;
      if (s.visibility === "public") return true;
      if (s.visibility === "approved_buyers" && buyerUnlocked) return true;
      return false;
    });

    const dateStr  = new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" });
    const filename = `im-report-${listingId.slice(0, 8)}-buyer.pdf`;

    const doc = new PDFDocument({ size: "A4", margin: 0, info: {
      Title: "Information Memorandum — Confidential Business",
      Author: "Exit360", Subject: "Confidential Business Information Memorandum",
    }});

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Cache-Control", "no-cache");
    doc.pipe(res);

    const PAGE_W = 595.28; const PAGE_H = 841.89; const MARGIN = 56;
    const CONTENT_W = PAGE_W - MARGIN * 2;
    const DARK = "#070F1C"; const DARK_MID = "#0F2040"; const BORDER = "#1E3A5C";
    const totalPages = 2 + sections.length;

    function addHF(pageNum: number) {
      doc.save().rect(0, 0, PAGE_W, 36).fill("#0A1828").restore();
      doc.font("Helvetica-Bold").fontSize(7).fillColor(MUTED).text("Confidential Business", MARGIN, 14, { width: CONTENT_W / 2 });
      doc.font("Helvetica").fontSize(7).fillColor(MUTED).text("Information Memorandum", MARGIN + CONTENT_W / 2, 14, { width: CONTENT_W / 2, align: "right" });
      doc.save().rect(0, PAGE_H - 36, PAGE_W, 36).fill("#0A1828").restore();
      doc.font("Helvetica").fontSize(7).fillColor(MUTED)
        .text("Confidential Business Profile · Generated by Exit360", MARGIN, PAGE_H - 22, { width: CONTENT_W - 80 })
        .text(`Page ${pageNum} of ${totalPages}`, MARGIN, PAGE_H - 22, { width: CONTENT_W, align: "right" });
    }

    // Cover
    doc.rect(0, 0, PAGE_W, PAGE_H).fill(DARK);
    doc.save().rect(0, 0, PAGE_W, 6).fill(BLUE_ACC).restore();
    doc.font("Helvetica-Bold").fontSize(9).fillColor(BLUE_ACC).text("CONFIDENTIAL", MARGIN, 60, { width: CONTENT_W, align: "center" });
    doc.font("Helvetica-Bold").fontSize(26).fillColor(WHITE).text("Information Memorandum", MARGIN, 86, { width: CONTENT_W, align: "center" });
    doc.font("Helvetica-Bold").fontSize(20).fillColor("#60A5FA").text("Confidential Business", MARGIN, 126, { width: CONTENT_W, align: "center" });
    doc.font("Helvetica").fontSize(10).fillColor(MUTED).text("Prepared by Exit360 · Verified Business Profile", MARGIN, 162, { width: CONTENT_W, align: "center" });
    doc.save().moveTo(MARGIN, 192).lineTo(PAGE_W - MARGIN, 192).lineWidth(1).strokeColor(BORDER).stroke().restore();
    doc.rect(MARGIN, 210, CONTENT_W, 80).fill(DARK_MID);
    doc.font("Helvetica").fontSize(8).fillColor(MUTED).text("LISTING REF.", MARGIN + 16, 226);
    doc.font("Helvetica-Bold").fontSize(12).fillColor(WHITE).text(listingId.slice(0, 8).toUpperCase(), MARGIN + 16, 238);
    doc.font("Helvetica").fontSize(8).fillColor(MUTED).text("DATE PREPARED", MARGIN + 16 + CONTENT_W / 2, 226);
    doc.font("Helvetica-Bold").fontSize(12).fillColor(WHITE).text(dateStr, MARGIN + 16 + CONTENT_W / 2, 238);
    doc.font("Helvetica").fontSize(9).fillColor(MUTED)
      .text("This document is confidential. Sections marked as Approved Buyers Only require identity verification.", MARGIN, 340, { width: CONTENT_W, align: "center" });
    doc.font("Helvetica-Bold").fontSize(16).fillColor(BLUE_ACC).text("Exit360", MARGIN, PAGE_H - 120, { width: CONTENT_W, align: "center" });

    // TOC
    doc.addPage({ size: "A4", margin: 0 }); doc.rect(0, 0, PAGE_W, PAGE_H).fill(DARK); addHF(2);
    doc.font("Helvetica-Bold").fontSize(16).fillColor(WHITE).text("Table of Contents", MARGIN, 56);
    doc.save().moveTo(MARGIN, 80).lineTo(PAGE_W - MARGIN, 80).lineWidth(0.5).strokeColor(BORDER).stroke().restore();
    let tocY = 94;
    sections.forEach((s, idx) => {
      if (tocY > PAGE_H - 80) return;
      doc.font("Helvetica-Bold").fontSize(8).fillColor(MUTED).text(`${String(idx + 1).padStart(2, "0")}`, MARGIN, tocY, { width: 24 });
      doc.font("Helvetica").fontSize(10).fillColor(LIGHT).text(s.title, MARGIN + 28, tocY, { width: CONTENT_W - 50 });
      doc.font("Helvetica").fontSize(8).fillColor(MUTED).text(`${idx + 3}`, MARGIN, tocY, { width: CONTENT_W, align: "right" });
      tocY += 18;
    });

    // Section pages
    sections.forEach((section, idx) => {
      doc.addPage({ size: "A4", margin: 0 }); doc.rect(0, 0, PAGE_W, PAGE_H).fill(DARK); addHF(idx + 3);
      const sY = 50;
      doc.save().rect(MARGIN, sY, 4, 26).fill(BLUE_ACC).restore();
      doc.font("Helvetica-Bold").fontSize(7).fillColor(BLUE_ACC).text(`${String(idx + 1).padStart(2, "0")}`, MARGIN + 10, sY + 2);
      doc.font("Helvetica-Bold").fontSize(15).fillColor(WHITE).text(section.title, MARGIN + 30, sY, { width: CONTENT_W - 30 });
      if (section.subtitle) doc.font("Helvetica").fontSize(9).fillColor(MUTED).text(section.subtitle, MARGIN + 30, sY + 22, { width: CONTENT_W - 30 });
      doc.save().moveTo(MARGIN, sY + 42).lineTo(PAGE_W - MARGIN, sY + 42).lineWidth(0.5).strokeColor(BORDER).stroke().restore();
      let bodyY = sY + 56;
      if (section.body) {
        for (const para of section.body.split(/\n{2,}/).filter(Boolean)) {
          if (bodyY > PAGE_H - 80) break;
          doc.font("Helvetica").fontSize(10).fillColor(LIGHT).text(para.trim(), MARGIN, bodyY, { width: CONTENT_W, lineGap: 3 });
          bodyY = doc.y + 10;
        }
      }
      const bullets = Array.isArray(section.bulletPoints) ? (section.bulletPoints as string[]) : [];
      for (const b of bullets) {
        if (!b.trim() || bodyY > PAGE_H - 80) continue;
        doc.save().circle(MARGIN + 5, bodyY + 4.5, 2.5).fill(BLUE_ACC).restore();
        doc.font("Helvetica").fontSize(10).fillColor(LIGHT).text(b.trim(), MARGIN + 16, bodyY, { width: CONTENT_W - 16, lineGap: 2 });
        bodyY = doc.y + 4;
      }
      if (!section.body && !bullets.length) {
        doc.font("Helvetica-Oblique").fontSize(9).fillColor(MUTED).text("This section has not yet been completed.", MARGIN, bodyY, { width: CONTENT_W });
      }
    });

    db.insert(reportExportsTable).values({
      listingId, ownerId: "public", exportType: "pdf_buyer_public",
    }).catch(() => {});

    doc.end();
  } catch (err: unknown) {
    const e = err as Error & { status?: number };
    logger.error({ err: e }, "Public PDF export failed");
    if (!res.headersSent) res.status(e.status ?? 500).json({ error: e.message ?? "Failed to generate PDF" });
  }
});

export default router;
