import { useEffect, useState } from "react";
import { useParams, Link } from "wouter";
import { ArrowLeft, Loader2, Check, X, Sparkles, Plus, Trash2, FileText, Eye } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Seo } from "@/components/Seo";

const TOKEN_KEY = "biz360_web_auth_token";
const inp = "w-full px-3 py-2 rounded-lg border border-border bg-background text-sm outline-none focus:border-primary/60";
const VIS = [
  { v: "public", label: "Public" },
  { v: "approved_buyers", label: "Approved buyers" },
  { v: "seller_only", label: "Seller only" },
  { v: "hidden", label: "Hidden" },
];

interface Section {
  id: string; sectionKey: string; title: string; subtitle?: string | null; body?: string | null;
  bulletPoints?: string[]; tableData?: { rows?: { label: string; value: string }[] } | null;
  visibility?: string; includeInPdf?: boolean; includeInHtml?: boolean; includeInApp?: boolean;
  isRequired?: boolean; isAutoGenerated?: boolean; status?: string; sortOrder?: number;
}

export function ReportBuilder() {
  const params = useParams();
  const listingId = params.listingId as string;
  const token = (() => { try { return localStorage.getItem(TOKEN_KEY); } catch { return null; } })();
  const auth = { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };

  const [sections, setSections] = useState<Section[]>([]);
  const [loading, setLoading] = useState(true);
  const [selId, setSelId] = useState<string | null>(null);
  const [savingId, setSavingId] = useState<string | null>(null);
  const [autoFill, setAutoFill] = useState<Record<string, any>>({});
  const [err, setErr] = useState<string | null>(null);

  async function load() {
    setLoading(true); setErr(null);
    try {
      let r = await fetch(`/api/report-sections/${listingId}`, { headers: auth });
      let d = await r.json();
      if (r.status === 403) { setErr("You don't own this listing, or its report record isn't set up yet."); setLoading(false); return; }
      let secs: Section[] = Array.isArray(d.sections) ? d.sections : [];
      if (secs.length === 0) {
        await fetch(`/api/report-sections/defaults/${listingId}`, { method: "POST", headers: auth });
        r = await fetch(`/api/report-sections/${listingId}`, { headers: auth });
        d = await r.json();
        secs = Array.isArray(d.sections) ? d.sections : [];
      }
      secs.sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0));
      setSections(secs);
      if (!selId && secs[0]) setSelId(secs[0].id);
      // Prefetch auto-fill suggestions (non-blocking).
      fetch(`/api/report-sections/auto-fill/${listingId}`, { headers: auth }).then((x) => x.json()).then((j) => setAutoFill(j.suggestions ?? {})).catch(() => {});
    } finally { setLoading(false); }
  }
  useEffect(() => { load(); /* eslint-disable-next-line */ }, [listingId]);

  const sel = sections.find((s) => s.id === selId) ?? null;
  const done = sections.filter((s) => s.status === "complete").length;

  function patchLocal(id: string, patch: Partial<Section>) { setSections((ss) => ss.map((s) => (s.id === id ? { ...s, ...patch } : s))); }
  async function saveSection(s: Section, extra?: Partial<Section>) {
    setSavingId(s.id);
    const body: any = {
      title: s.title, subtitle: s.subtitle ?? "", body: s.body ?? "", bulletPoints: s.bulletPoints ?? [],
      tableData: s.tableData ?? { rows: [] }, visibility: s.visibility ?? "public",
      includeInPdf: s.includeInPdf !== false, includeInHtml: s.includeInHtml !== false, includeInApp: s.includeInApp !== false,
      ...extra,
    };
    try {
      const r = await fetch(`/api/report-sections/${s.id}`, { method: "PATCH", headers: auth, body: JSON.stringify(body) });
      if (r.ok) { const d = await r.json(); if (d.section) patchLocal(s.id, d.section); }
    } finally { setSavingId(null); }
  }
  function applyAutoFill(s: Section) {
    const sug = autoFill[s.sectionKey];
    if (!sug) return;
    patchLocal(s.id, {
      body: sug.suggestedBody ?? s.body,
      bulletPoints: Array.isArray(sug.suggestedBullets) && sug.suggestedBullets.length ? sug.suggestedBullets : s.bulletPoints,
      tableData: sug.tableData ?? s.tableData,
    });
  }

  if (!token) return <div className="min-h-screen grid place-items-center text-foreground p-8"><div className="text-center"><p className="mb-3">Please sign in.</p><Link href="/seller"><Button className="theme-btn-gradient border-0">Seller dashboard</Button></Link></div></div>;
  if (loading) return <div className="min-h-screen grid place-items-center text-muted-foreground"><Loader2 className="animate-spin mr-2" /> Loading report builder…</div>;

  return (
    <div className="min-h-screen text-foreground">
      <Seo title="Report Builder | EXIT360" description="Author your business report / IM." path={`/seller/report/${listingId}`} />
      <div className="sticky top-0 z-30 flex items-center gap-3 px-4 py-3 border-b border-border bg-card/80 backdrop-blur">
        <Link href="/seller" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft size={16} /> Dashboard</Link>
        <span className="font-bold">Report builder</span>
        <div className="ml-auto flex items-center gap-3">
          <span className="text-xs text-muted-foreground">{done}/{sections.length} complete</span>
          <Link href={`/reports/${listingId}`}><Button size="sm" variant="outline" className="gap-1.5"><Eye size={14} /> Preview</Button></Link>
        </div>
      </div>

      {err ? (
        <div className="max-w-2xl mx-auto p-10 text-center text-muted-foreground">{err}</div>
      ) : (
        <div className="grid lg:grid-cols-[280px_1fr] min-h-[calc(100vh-57px)]">
          {/* Section list */}
          <div className="border-r border-border overflow-y-auto themed-scroll lg:sticky lg:top-[57px]" style={{ maxHeight: "calc(100vh - 57px)" }}>
            {sections.map((s) => (
              <button key={s.id} onClick={() => setSelId(s.id)} className={`w-full text-left px-3 py-2.5 border-b border-border/50 ${s.id === selId ? "bg-primary/10" : "hover:bg-muted/30"}`}>
                <div className="flex items-center gap-2">
                  <span className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${s.status === "complete" ? "bg-emerald-400" : (s.body ? "bg-amber-400" : "bg-muted-foreground/40")}`} />
                  <span className="text-sm truncate flex-1">{s.title}</span>
                  {s.isRequired && <span className="text-[9px] text-primary/70">req</span>}
                </div>
              </button>
            ))}
          </div>

          {/* Editor */}
          <div className="p-4 md:p-6 max-w-3xl">
            {sel && (
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between gap-2 flex-wrap">
                  <h2 className="text-lg font-bold">{sel.title}</h2>
                  <div className="flex items-center gap-2">
                    {autoFill[sel.sectionKey] && <Button size="sm" variant="outline" className="gap-1.5" onClick={() => applyAutoFill(sel)}><Sparkles size={13} /> Auto-fill from app data</Button>}
                    <Button size="sm" onClick={() => saveSection(sel)} disabled={savingId === sel.id} className="theme-btn-gradient border-0">{savingId === sel.id ? "Saving…" : "Save"}</Button>
                  </div>
                </div>

                <label className="text-xs font-semibold text-muted-foreground">Title<input value={sel.title} onChange={(e) => patchLocal(sel.id, { title: e.target.value })} className={`${inp} mt-1 font-normal`} /></label>
                <label className="text-xs font-semibold text-muted-foreground">Subtitle<input value={sel.subtitle ?? ""} onChange={(e) => patchLocal(sel.id, { subtitle: e.target.value })} className={`${inp} mt-1 font-normal`} /></label>
                <label className="text-xs font-semibold text-muted-foreground">Body
                  <textarea value={sel.body ?? ""} onChange={(e) => patchLocal(sel.id, { body: e.target.value })} rows={8} className={`${inp} mt-1 font-normal`} placeholder="Write this section…" />
                  <span className="text-[11px] text-muted-foreground">{(sel.body ?? "").trim().split(/\s+/).filter(Boolean).length} words</span>
                </label>

                <div>
                  <span className="text-xs font-semibold text-muted-foreground">Key points</span>
                  {(sel.bulletPoints ?? []).map((bp, i) => (
                    <div key={i} className="flex gap-1.5 mt-1">
                      <input value={bp} onChange={(e) => { const a = [...(sel.bulletPoints ?? [])]; a[i] = e.target.value; patchLocal(sel.id, { bulletPoints: a }); }} className={inp} />
                      <button onClick={() => { const a = [...(sel.bulletPoints ?? [])]; a.splice(i, 1); patchLocal(sel.id, { bulletPoints: a }); }} className="text-red-400"><X size={14} /></button>
                    </div>
                  ))}
                  <button onClick={() => patchLocal(sel.id, { bulletPoints: [...(sel.bulletPoints ?? []), ""] })} className="text-primary text-xs mt-1.5"><Plus size={12} className="inline" /> Add point</button>
                </div>

                <div>
                  <span className="text-xs font-semibold text-muted-foreground">Detail rows (label / value)</span>
                  {((sel.tableData?.rows) ?? []).map((row, i) => (
                    <div key={i} className="flex gap-1.5 mt-1">
                      <input value={row.label} onChange={(e) => { const rows = [...(sel.tableData?.rows ?? [])]; rows[i] = { ...rows[i], label: e.target.value }; patchLocal(sel.id, { tableData: { rows } }); }} placeholder="Label" className={inp} />
                      <input value={row.value} onChange={(e) => { const rows = [...(sel.tableData?.rows ?? [])]; rows[i] = { ...rows[i], value: e.target.value }; patchLocal(sel.id, { tableData: { rows } }); }} placeholder="Value" className={inp} />
                      <button onClick={() => { const rows = [...(sel.tableData?.rows ?? [])]; rows.splice(i, 1); patchLocal(sel.id, { tableData: { rows } }); }} className="text-red-400"><Trash2 size={14} /></button>
                    </div>
                  ))}
                  <button onClick={() => patchLocal(sel.id, { tableData: { rows: [...(sel.tableData?.rows ?? []), { label: "", value: "" }] } })} className="text-primary text-xs mt-1.5"><Plus size={12} className="inline" /> Add row</button>
                </div>

                <div className="grid sm:grid-cols-2 gap-3 border-t border-border pt-4">
                  <label className="text-xs font-semibold text-muted-foreground">Visibility<select value={sel.visibility ?? "public"} onChange={(e) => patchLocal(sel.id, { visibility: e.target.value })} className={`${inp} mt-1 font-normal`}>{VIS.map((v) => <option key={v.v} value={v.v}>{v.label}</option>)}</select></label>
                  <div className="flex flex-wrap items-end gap-3">
                    <Chk label="In PDF" on={sel.includeInPdf !== false} onToggle={() => patchLocal(sel.id, { includeInPdf: !(sel.includeInPdf !== false) })} />
                    <Chk label="In web" on={sel.includeInHtml !== false} onToggle={() => patchLocal(sel.id, { includeInHtml: !(sel.includeInHtml !== false) })} />
                    <Chk label="In app" on={sel.includeInApp !== false} onToggle={() => patchLocal(sel.id, { includeInApp: !(sel.includeInApp !== false) })} />
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <Button size="sm" onClick={() => saveSection(sel)} disabled={savingId === sel.id} className="theme-btn-gradient border-0">{savingId === sel.id ? "Saving…" : "Save section"}</Button>
                  <Button size="sm" variant="outline" onClick={() => saveSection(sel, { status: sel.status === "complete" ? "draft" : "complete" })}>{sel.status === "complete" ? "Mark incomplete" : <><Check size={14} className="mr-1" /> Mark complete</>}</Button>
                  {sel.isAutoGenerated && <span className="text-[11px] text-muted-foreground inline-flex items-center gap-1"><FileText size={11} /> Auto-generated in the report from your app data</span>}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function Chk({ label, on, onToggle }: { label: string; on: boolean; onToggle: () => void }) {
  return <button onClick={onToggle} className="inline-flex items-center gap-1.5 text-sm"><span className={`w-4 h-4 rounded border grid place-items-center ${on ? "theme-btn-gradient border-0" : "border-border"}`}>{on && <Check size={11} className="text-primary-foreground" />}</span>{label}</button>;
}
