import {
  pgTable,
  uuid,
  text,
  boolean,
  integer,
  numeric,
  timestamp,
  jsonb,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// ─── report_sections ─────────────────────────────────────────────────────────
// One row per section per listing. section_key is a stable string identifier
// (e.g. "executive_summary", "lease_premises_summary") that drives section
// ordering, CSV import/export, and auto-fill.

export const reportSectionsTable = pgTable(
  "report_sections",
  {
    id:             uuid("id").primaryKey().defaultRandom(),
    listingId:      text("listing_id").notNull(),
    ownerId:        text("owner_id").notNull(),
    sectionKey:     text("section_key").notNull(),
    title:          text("title").notNull(),
    subtitle:       text("subtitle"),
    body:           text("body"),
    bulletPoints:   jsonb("bullet_points").$type<string[]>().default([]),
    tableData:      jsonb("table_data"),
    chartData:      jsonb("chart_data"),
    aiInstruction:  text("ai_instruction"),
    sellerNotes:    text("seller_notes"),
    // visibility: public | approved_buyers | seller_only | hidden
    visibility:     text("visibility").notNull().default("public"),
    includeInPdf:   boolean("include_in_pdf").notNull().default(true),
    includeInHtml:  boolean("include_in_html").notNull().default(true),
    includeInApp:   boolean("include_in_app").notNull().default(true),
    sortOrder:      integer("sort_order").notNull().default(0),
    isRequired:     boolean("is_required").notNull().default(false),
    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
    isAiEditable:   boolean("is_ai_editable").notNull().default(true),
    // status: empty | draft | complete | needs_review
    status:         text("status").notNull().default("empty"),
    // data_source: seller_supplied | app_generated | csv_imported | ai_drafted | mixed
    dataSource:     text("data_source").notNull().default("seller_supplied"),
    lastUpdatedAt:  timestamp("last_updated_at").defaultNow(),
    createdAt:      timestamp("created_at").defaultNow(),
  },
  (t) => [
    uniqueIndex("report_sections_listing_section_idx").on(t.listingId, t.sectionKey),
  ]
);

export type ReportSection = typeof reportSectionsTable.$inferSelect;
export type InsertReportSection = typeof reportSectionsTable.$inferInsert;

// ─── report_versions ─────────────────────────────────────────────────────────
// Snapshot of all section content at a point in time, created when a seller
// publishes or exports. Allows version history and rollback.

export const reportVersionsTable = pgTable("report_versions", {
  id:               uuid("id").primaryKey().defaultRandom(),
  listingId:        text("listing_id").notNull(),
  ownerId:          text("owner_id").notNull(),
  versionNumber:    integer("version_number").notNull().default(1),
  title:            text("title"),
  // status: draft | published | archived
  status:           text("status").notNull().default("draft"),
  generatedHtmlUrl: text("generated_html_url"),
  generatedPdfUrl:  text("generated_pdf_url"),
  snapshotJson:     jsonb("snapshot_json"),
  createdBy:        text("created_by"),
  createdAt:        timestamp("created_at").defaultNow(),
});

export type ReportVersion = typeof reportVersionsTable.$inferSelect;

// ─── report_csv_imports ───────────────────────────────────────────────────────
// Audit trail for each CSV import — file name, row counts, and outcome summary.

export const reportCsvImportsTable = pgTable("report_csv_imports", {
  id:            uuid("id").primaryKey().defaultRandom(),
  listingId:     text("listing_id").notNull(),
  ownerId:       text("owner_id").notNull(),
  fileName:      text("file_name"),
  rowCount:      integer("row_count").default(0),
  matchedCount:  integer("matched_count").default(0),
  unknownKeys:   jsonb("unknown_keys").$type<string[]>().default([]),
  // status: preview | complete | failed
  status:        text("status").notNull().default("complete"),
  importSummary: jsonb("import_summary"),
  createdAt:     timestamp("created_at").defaultNow(),
});

export type ReportCsvImport = typeof reportCsvImportsTable.$inferSelect;

// ─── report_exports ───────────────────────────────────────────────────────────
// Records each PDF/HTML export action so sellers can review past exports.

export const reportExportsTable = pgTable("report_exports", {
  id:         uuid("id").primaryKey().defaultRandom(),
  listingId:  text("listing_id").notNull(),
  ownerId:    text("owner_id").notNull(),
  versionId:  uuid("version_id"),
  // export_type: pdf_seller | pdf_buyer | html | csv
  exportType: text("export_type").notNull(),
  fileUrl:    text("file_url"),
  createdAt:  timestamp("created_at").defaultNow(),
});

export type ReportExport = typeof reportExportsTable.$inferSelect;

// ─── report_access_logs ───────────────────────────────────────────────────────
// Buyer-side event log: who viewed what section, clicked the tour, requested
// access, downloaded the PDF, etc. Used to improve seller analytics.

export const reportAccessLogsTable = pgTable("report_access_logs", {
  id:         uuid("id").primaryKey().defaultRandom(),
  listingId:  text("listing_id").notNull(),
  // event_type: section_viewed | pdf_downloaded | tour_clicked | access_requested
  //             financials_unlocked | contact_clicked | inspection_booked | document_requested
  eventType:  text("event_type").notNull(),
  sectionKey: text("section_key"),
  buyerId:    text("buyer_id"),
  buyerPhone: text("buyer_phone"),
  buyerIp:    text("buyer_ip"),
  userAgent:  text("user_agent"),
  metadata:   jsonb("metadata"),
  createdAt:  timestamp("created_at").defaultNow(),
});

export type ReportAccessLog = typeof reportAccessLogsTable.$inferSelect;

// ─── report_images ────────────────────────────────────────────────────────────
// Seller-uploaded static images for the IM report and PDF export.
// Distinct from panorama tour images — panoramics may never be set as cover.
//
// Priority chain for cover hero:
//   is_primary=true (non-panoramic) → image_role=listing_hero → exterior →
//   KV/listing hero_image_url fallback (non-panoramic only) → gradient
//
// source_type tracks origin: uploaded | listing_photo | tour_thumbnail
// deleted_at implements soft-delete; rows with deleted_at set are excluded from
// all reads. Cloudinary assets are only purged when source_type='uploaded'.

export const reportImagesTable = pgTable("report_images", {
  id:                     uuid("id").primaryKey().defaultRandom(),
  listingId:              text("listing_id").notNull(),
  userId:                 text("user_id").notNull(),
  cloudinaryPublicId:     text("cloudinary_public_id").notNull(),
  cloudinaryUrl:          text("cloudinary_url").notNull(),
  cloudinarySecureUrl:    text("cloudinary_secure_url").notNull(),
  originalFilename:       text("original_filename"),
  displayName:            text("display_name"),
  // image_role: listing_hero | cover_secondary | exterior | interior | equipment
  //             | team | product | 360_preview | other
  // Panoramic images (aspect_ratio > 2.2) may only have role = 360_preview
  imageRole:              text("image_role").notNull().default("other"),
  caption:                text("caption"),
  altText:                text("alt_text"),
  // Only one non-panoramic image per listing may have is_primary = true
  // Enforced at the API layer: setting to true clears all others first
  isPrimary:              boolean("is_primary").notNull().default(false),
  includeInPdf:           boolean("include_in_pdf").notNull().default(true),
  includeInHtml:          boolean("include_in_html").notNull().default(true),
  includeInBuyerReport:   boolean("include_in_buyer_report").notNull().default(true),
  includeInSellerReport:  boolean("include_in_seller_report").notNull().default(true),
  // section_key links this image to a specific report section (e.g. 'business_overview')
  sectionKey:             text("section_key"),
  sortOrder:              integer("sort_order").notNull().default(0),
  width:                  integer("width"),
  height:                 integer("height"),
  // Stored as numeric string to avoid floating-point issues; parse with parseFloat()
  aspectRatio:            numeric("aspect_ratio"),
  fileSize:               integer("file_size"),
  mimeType:               text("mime_type"),
  // source_type: uploaded | listing_photo | tour_thumbnail
  sourceType:             text("source_type").notNull().default("uploaded"),
  // source_ref_id: Cloudinary public_id of the original asset (for non-upload sources)
  sourceRefId:            text("source_ref_id"),
  // Panoramic = aspect_ratio > 2.2; enforced at API layer; only role=360_preview allowed
  isPanoramic:            boolean("is_panoramic").notNull().default(false),
  createdAt:              timestamp("created_at").defaultNow(),
  updatedAt:              timestamp("updated_at").defaultNow(),
  // Soft delete — set by DELETE endpoint; rows with deletedAt are excluded from all reads
  deletedAt:              timestamp("deleted_at"),
});

export type ReportImage = typeof reportImagesTable.$inferSelect;
export type InsertReportImage = typeof reportImagesTable.$inferInsert;
